# MAIN CONFIGURATION

app.name = GetSkinsInfo
app.uuid = 444242a5-6721-4e18-a82f-c762a3b5bd13
app.version = 1

# APP
app.namespace = app
app.mainForm = 
app.showMainForm = 1

app.fx.splash.autoHide = 0